Final

diff --git a/.github/workflows/ant.yml b/.github/workflows/ant.yml
--- a/.github/workflows/ant.yml
+++ b/.github/workflows/ant.yml
@@ -6,8 +6,6 @@ name: Java CI
 on:
   push:
     branches: [ master ]
-  pull_request:
-    branches: [ master ]
 
 jobs:
   build:
@@ -18,38 +16,38 @@ jobs:
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
-    # - shell: bash
-    #   name: Build fhir-ru site
-    #   run: |
-    #     cp -R source.ru/* source
-    #     set -ev
-    #     git fetch --depth 20
-    #     [ -d publish ] && rm -rf publish
-    #     NAME="Непрерывная интеграционная сборка"
-    #     SVNREV=$(git rev-parse --short HEAD)
-    #     antBuild (){
-    #      ant -Dargs="./publish.sh -svn $SVNREV -name \'$NAME\' -url http://build.fhir.org/  -post-pr"
-    #        checkStatus
-    #     }
-    #     checkStatus (){
-    #      nf=`find publish -maxdepth 1 -type f | wc -l`
-    #      if [ "$nf" -lt "100" ] ; then
-    #         echo "< 100 files produced: bailing!"
-    #         exit 1
-    #      fi
-    #      if [ $? -eq 0 -a ! -f fhir-error-dump.txt ]
-    #      then
-    #        echo "Build status OK"
-    #      else
-    #        echo "error dump:"
-    #        cat fhir-error-dump.txt
-    #        exit 1
-    #      fi
-    #     }
-    #     antBuild
+    - shell: bash
+      name: Build fhir-ru site
+      run: |
+        cp -R source.ru/* source
+        set -ev
+        git fetch --depth 20
+        [ -d publish ] && rm -rf publish
+        NAME="Непрерывная интеграционная сборка"
+        SVNREV=$(git rev-parse --short HEAD)
+        antBuild (){
+         ant -Dargs="./publish.sh -svn $SVNREV -name \'$NAME\' -url http://build.fhir.org/  -post-pr"
+           checkStatus
+        }
+        checkStatus (){
+         nf=`find publish -maxdepth 1 -type f | wc -l`
+         if [ "$nf" -lt "100" ] ; then
+            echo "< 100 files produced: bailing!"
+            exit 1
+         fi
+         if [ $? -eq 0 -a ! -f fhir-error-dump.txt ]
+         then
+           echo "Build status OK"
+         else
+           echo "error dump:"
+           cat fhir-error-dump.txt
+           exit 1
+         fi
+        }
+        antBuild
     - name: Publish generated content to GitHub Pages
       shell: bash
-      working-directory: ./source
+      working-directory: ./publish
       run: |
         git init
         git config user.email "github-builder@fhir.org"
@@ -58,4 +56,4 @@ jobs:
         ../remove_files_larger_than_100mg_for_gh_pages_compatibility.sh
         git add -A .
         git commit -m "GitHub Actions docs build"
-        git push origin master
+        git push -f origin master
